services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: carteira
      POSTGRES_PASSWORD: carteira123
      POSTGRES_DB: carteira_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U carteira"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    command: bash -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DB_USER: carteira
      DB_PASSWORD: carteira123
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: carteira_db
      SECRET_KEY: supersecretkey
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      API_V1_STR: /api/v1
      DEBUG: "True"
      # Configurações OAuth
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-seu_google_client_id}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:-seu_google_client_secret}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI:-http://localhost:8000/api/v1/oauth/google/callback}
      FACEBOOK_CLIENT_ID: ${FACEBOOK_CLIENT_ID:-seu_facebook_client_id}
      FACEBOOK_CLIENT_SECRET: ${FACEBOOK_CLIENT_SECRET:-seu_facebook_client_secret}
      FACEBOOK_REDIRECT_URI: ${FACEBOOK_REDIRECT_URI:-http://localhost:8000/api/v1/oauth/facebook/callback}
      FRONTEND_REDIRECT_URL: ${FRONTEND_REDIRECT_URL:-http://localhost:3000/auth/callback}
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: 